{  test: true,
  list: [1,`two`,[3],{ value : 4  } ],
  object: { test : `yes` ,number : 2  } ,
  module: {  as: {  path: ((function(m) {  return typeof m.default === 'function' ? m.default:m })(require('module/as/path'))),
  relative: {  path: ((function(m) {  return typeof m.default === 'function' ? m.default:m })(require('./module/with/relative/../path')))}}},
  array: {  of: {  modules: [((function(m) {  return typeof m.default === 'function' ? m.default:m })(require('one'))),((function(m) {  return typeof m.default === 'function' ? m.default:m })(require('./1/2/3'))),((function(m) {  return m.one })(require('other/one')))]}},
  call: {  member: {  noargs: ((function(m) {  return m.member })(require('module/with/member')))()},
  noargs: ((function(m) {  return typeof m.default === 'function' ? m.default:m })(require('funcs')))()},
  complex: {  dict: { main : { connector : ((function(m) {  return m.connector })(require('path/to/connector'))) ,options : { collection : `websessions` ,autoRemove : `interval` ,autoRemoveInterval : process.env['AUTO_REMOVE_INTERVAL']  }   }   } },
  tendrill: {  app: {  filters: {  session: {  enabled: true,
  options: { httpOnly : true  } }},
  modules: { www : ((function(m) {  return typeof m.default === 'function' ? m.default:m })(require('lims/modules/www')))  } },
  filters: {  csrf: {  enabled: true}}}} 