export declare const tests: {
    'should recognize booleans': string;
    'should recognize lists': string;
    'should recognize dicts': string;
    'should recognize strings': string;
    'should recognize module members': string;
    'should recognize org module members': string;
    'should recognize dotted paths': string;
    'should recognize lists of members': string;
    'should recognize partially applied modules': string;
    'should recognize empty partially applied modules': string;
    'should recognize partially applied members': string;
    'should recognize empty partially applied members': string;
    'should recognize variables': string;
    'should recognize environment variables': string;
    'should recognize comments': string;
    'should recognize includes': string;
    'should allow complex dicts': string;
    'should all together now': string;
    'should allow filters on vars': string;
    'should allow filters on envars': string;
    'should allow objects with paths': string;
    'should allow string literal paths': string;
    'should merge paths': string;
    'should import nested imports': string;
    'should allow modules members in calls with dict args': string;
};
